# https://wiki.openstreetmap.org/wiki/Map_features
specification:
  # Re-used colors
  rgbaColors:
    white: "#ffffff"
    blue: "#a9d3de"
    gray: "#d8d0c9"
    red: "#0000ff"
    motorway: "#e990a0"
    trunk: "#fbc0ab"
    primary: "#fdd6a1"
    secondary: "#f6fabb"
    path_brown: "#b99855"
    light_green: "#cdebb0"
    green: "c8d7ab"
    dark_green: "#add19e"
    sand: "#fff1bb"
    coast: "#f2efe9"
    salmon: "#f5dcba"
    fun_green: "#dffce2"
    area_gray: "#e0dfdf"
    beige: "#d6d99f"
    pale_green: "#eff0d5"
    black: "#000000"
features:
  building:
    def:
      rgba: "gray"
  emergency:
    individuals:
      ambulance_station:
        rgba: "red"
      landing_site:
        rgba: "red"
  highway:
    groupings:
      - tags:
          - "motorway"
          - "motorway_link"
        rgba: "motorway"
        stroke: 7
      - tags:
          - "trunk"
          - "trunk_link"
        rgba: "trunk"
        stroke: 6
      - tags:
          - "primary"
          - "primary_link"
        rgba: "primary"
        stroke: 5
      - tags:
          - "secondary"
          - "secondary_link"
        rgba: "secondary"
        stroke: 4
      - tags:
          - "tertiary"
          - "tertiary_link"
        rgba: "white"
        stroke: 3
      - tags:
          - "unclassified"
          - "residential"
          - "living_street"
          - "service"
          - "road"
        rgba: "white"
        stroke: 2
      - tags:
          - "footway"
          - "bridleway"
          - "steps"
          - "path"
          - "track"
        rgba: "path_brown"
        stroke: 1
  landuse:
    groupings:
      # Greens
      - tags:
          - "meadow"
          - "grass"
        rgba: "light_green"
      - tags:
          - "forest"
        rgba: "dark_green"
      # Areas
      - tags:
          - "residential"
        rgba: "area_gray"
      - tags:
          - "farmyard"
        rgba: "salmon"
      - tags:
          - "farmland"
        rgba: "pale_green"
      - tags:
          - "recreation_ground"
        rgba: "fun_green"
  leisure:
    groupings:
      # Greens
      - tags:
          - "park"
          - "pitch"
        rgba: "fun_green"
  natural:
    groupings:
      # Greens
      - tags:
          - "grassland"
        rgba: "light_green"
      - tags:
          - "scrub"
          - "wood"
          - "wetland"
        rgba: "green"
      - tags:
          - "wood"
          - "wetland"
        rgba: "dark_green"
      - tags:
          - "heath"
        rgba: "beige"
      # Waters
      - tags:
          - "bay"
          - "water"
        rgba: "blue"
      # Borders
      - tags:
          - "coastline"
          - "peninsula"
        rgba: "coast"
      - tags:
          - "sand"
          - "beach"
        rgba: "sand"
  water:
    def:
      rgba: "blue"
  waterway:
    groupings:
      - tags:
          - "river"
          - "riverbank"
          - "stream"
          - "canal"
          - "drain"
          - "ditch"
        rgba: "blue"
        stroke: 3
infoToKeep:
  - "building:levels"
  - "height"
  - "maxspeed"
  - "oneway"